### ISSUE TITLE
Bug: UI not working properly - can't use it AND can't uninstall it

### ISSUE THREAD

**Issue by silviotobias** [bitgapp/eqMac#323]
Hi, I would love to use eqMac but... it's not happening. The UI is not working properly, as you can see by the attached screenshots =/ The sliders flash once than disappear. Nothing becomes clickable.
I considered to reinstall it, but it's also not possible to uninstall - it simply freezes after trying to, showing a small grey box on the center (the same happens when clicking on the quit icon)
Any ideas?

![Screen Shot 2020-06-25 at 02 25 05](https://user-images.githubusercontent.com/67406507/85661937-a8fcb880-b68d-11ea-9da5-88acddf4538f.png)
![Screen Shot 2020-06-25 at 02 25 25](https://user-images.githubusercontent.com/67406507/85661931-a7cb8b80-b68d-11ea-8722-cd0e7c9290cc.png)
![Screen Shot 2020-06-25 at 02 27 00](https://user-images.githubusercontent.com/67406507/85661923-a601c800-b68d-11ea-8aa5-1dd4843a7ca9.png)

 - Audio device used for playback: Macbook speaker
 - macOS Version 10.12.6
 - eqMac UI Version 1.2.0

**Comment by t0mn** [comment]
Try adding it to your firewall rules (allow), and then reinstall.  After it is working you can upgrade to the latest and remove the firewall rule.  Worked for me.

**Comment by silviotobias** [comment]
> Try adding it to your firewall rules (allow), and then reinstall. After it is working you can upgrade to the latest and remove the firewall rule. Worked for me.

Hi, I would try to reinstall but to do so I need to uninstall it first - and the uninstall button is not working, as showed above=/
I trashed it before, but when I reinstalled nothing has changed.
Also, I've just downloaded it from https://eqmac.app - that's not the latest version? Why upgrade?

**Comment by nodeful** [comment]
It looks to me that your WebKit framework that's preinstalled with your macOS version is very out of date. What version of Safari browser is installed on your machine?

**Comment by silviotobias** [comment]
Safari 12.1.2
According to Browserspy, my webkit version is 537.36

![image](https://user-images.githubusercontent.com/67406507/85906887-1c194280-b7e6-11ea-9ee9-5f25cded5444.png)

**Comment by nodeful** [comment]
Mine is 605.1.15 :(

**Comment by nodeful** [comment]
And Safari 13.0
Are you able to update Safari? That should update WebKit framework globally on your Mac

**Comment by silviotobias** [comment]
> And Safari 13.0
> Are you able to update Safari? That should update WebKit framework globally on your Mac

Unfortunately no=( My Macbook is running OS Sierra, no updates available on App Store for me...
Since I can't use it, is there a way to properly uninstall it? I trashed it before, but the driver will keep on if I don't run the uninstall script, right?
Thanks

**Comment by nodeful** [comment]
Give me a moment I will try to rebuild the UI with older Safari target in mind. Can't guarantee much but lemme try

**Comment by silviotobias** [comment]
Oh thank you=))

**Comment by nodeful** [comment]
I have deployed a new version of the UI (no need to update the app it's over the air update as long as you have Internet) but the cache is being a twat and is not purging, have to go to bed now but please keep restarting eqMac and check the UI version (question mark top right corner) should say 1.2.1 (Remote).

**Comment by nodeful** [comment]
Any luck with the new UI version?

**Comment by silviotobias** [comment]
Hi, I couldn't try it yet - I'll tell you as soon as I get back to my computer, thank you!=)

**Comment by silviotobias** [comment]
Hi, I restarted the app but the UI issue is still there=/
The only features working are FAQ / Report / Dock-Both-Status Bar / Reinstall Driver. No other buttons / menus work...

![Screen Shot 2020-06-28 at 14 11 25](https://user-images.githubusercontent.com/67406507/85953867-eee5a500-b949-11ea-8b06-15cfb67649c4.png)

And it's still freezing when I try to uninstall or quit it by clicking on the power button top right

![Screen Shot 2020-06-28 at 14 13 28](https://user-images.githubusercontent.com/67406507/85953874-f311c280-b949-11ea-8275-fe1e09cde1ad.png)

I've also experienced a few crashes when opening...

![Screen Shot 2020-06-28 at 14 11 55](https://user-images.githubusercontent.com/67406507/85953999-babeb400-b94a-11ea-9764-b9f0d91c7510.png)

=(

**Comment by nodeful** [comment]
huh this is really weird. I've used BrowserStack to simulate Safari 10 and the app looks absolutely fine there :( Seems like you have one of a kind WebKit problem. What's the reason of staying on Sierra for so long?

**Comment by FrictionlessFusion** [comment]
Hi. New to the site and conversation (apologies for newbie errors). Having this exact problem with identical symptoms on Sierra (10.12.6). Thanks.

**Comment by silviotobias** [comment]
> huh this is really weird. I've used BrowserStack to simulate Safari 10 and the app looks absolutely fine there :( Seems like you have one of a kind WebKit problem. What's the reason of staying on Sierra for so long?

Macbook Pro late 2011=/

**Comment by silviotobias** [comment]
Hi again
Since I can't use it because of my old old computer, could you tell what elements were installed so I can delete them manually?

**Comment by FrictionlessFusion** [comment]
Hi
Likewise, I'd also appreciate specific instructions to properly remove the eqMac elements from my system. 
Thanks

**Comment by nodeful** [comment]
I managed to setup an environment where I was able to test the issues with the UI on macOS 10.12. Today I pushed another version of UI and everything should be working on 10.12 now. No need to redownload eqMac if you still have it installed, just run it :)
